/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import DAOs.DAO_Categorias;
import DAOs.DAO_Productos;
import DAOs.DAO_Proveedores;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import modelo.Productos;
import modelo.ReportGenerator1;

/**
 *
 * @author user
 */
public class vCrearReportes extends javax.swing.JFrame {

    String encabezados[] = {"Prod ID", "Nombre", "Precio", "In Stock", "Foto", "Categoría", "Proveedor"};
    String encabezadosProvs[] = {"ID", "Nombre Proveedor"};
    String nomCategorias[] = {"ID", "Nombre", "Descripción"};
    DefaultTableModel mModeloTabla = new DefaultTableModel();
    DAOs.DAO_Productos daoProds = new DAO_Productos();
    DAOs.DAO_Categorias daoCategs = new DAO_Categorias();
    DAOs.DAO_Proveedores daoProvs = new DAO_Proveedores();
    int numReporte = 0;

    ArrayList<Object[]> datos = new ArrayList<>();
    /**
     * Creates new form vCrearReportes
     */
    public vCrearReportes() {
        initComponents();
        
        for(String nombre : encabezados) {
            mModeloTabla.addColumn(nombre);
        }
        
        limpiarTabla();
        cargarProductos();
    }
    
    private void limpiarTabla() {
        mModeloTabla.setNumRows(0);
    }
    
    private void cargarProductos() {
        ArrayList<String> nombresCateg = daoCategs.getNombres();
        ArrayList<String> nombresProvs = daoProvs.getNombres();
        
        tblDatos.setDefaultRenderer(Object.class, new RenderImagen());

        ArrayList Imagenes;
        //ImagenAlmacen mImagenAlmacen;
        Productos producto;

        Object Datos[] = new Object[7];
        Imagenes = daoProds.FiltrarImagenes("", 0, 0, 0);

        if (Imagenes != null) {
            for (int i = 0; i < Imagenes.size(); i++) {
                producto = (Productos) Imagenes.get(i);
                Datos[0] = String.valueOf(producto.getProducto_id());
                Datos[1] = producto.getNombre_producto();
                Datos[2] = producto.getPrecio();
                Datos[3] = producto.getInStock();
                try {
                    byte[] imagen = producto.getFoto();
                    BufferedImage bufferedImage = null;
                    InputStream inputStream = new ByteArrayInputStream(imagen);
                    bufferedImage = ImageIO.read(inputStream);
                    ImageIcon mIcono = new ImageIcon(bufferedImage.getScaledInstance(60, 60, 0));
                    Datos[4] = new JLabel(mIcono);
                } catch (Exception e) {
                    Datos[4] = new JLabel("No imagen");
                }


                Datos[5] = nombresCateg.get(producto.getCategoria_id() - 1);
                Datos[6] = nombresProvs.get(producto.getProveedor_id() - 1);

                mModeloTabla.addRow(Datos);
            }

            tblDatos.setModel(mModeloTabla);
            tblDatos.setRowHeight(60);
            tblDatos.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblDatos.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblDatos.getColumnModel().getColumn(2).setPreferredWidth(60);

        }
    }
    
    private void cargarTabla(String nombresEncabezados[]) {
        DefaultTableModel modelo = new DefaultTableModel(nombresEncabezados, 0);
        modelo.setNumRows(0); // Limpiando el modelo
        
        if(numReporte == 1) { // Si es proveedor
            this.datos = this.daoProvs.seleccionar();
        }else if(numReporte == 2) { // Si son las categorías
            this.datos = this.daoCategs.seleccionar();
        }
        
        for(Object[] fila : this.datos) {
            modelo.addRow(fila);
        }
        
        this.tblDatos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnProv = new javax.swing.JButton();
        btnCateg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Crear Reportes");

        btnVolver.setText("Volver al menú");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jButton1.setText("Crear reporte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnProductos.setText("Ver productos");
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosMouseClicked(evt);
            }
        });

        btnProv.setText("Ver proveedores");
        btnProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProvMouseClicked(evt);
            }
        });

        btnCateg.setText("Ver categorías");
        btnCateg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnProductos)
                .addGap(18, 18, 18)
                .addComponent(btnProv)
                .addGap(18, 18, 18)
                .addComponent(btnCateg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVolver))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProductos)
                    .addComponent(btnProv)
                    .addComponent(btnCateg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseClicked
        // TODO add your handling code here:
        numReporte = 0;
        limpiarTabla();
        cargarProductos();
    }//GEN-LAST:event_btnProductosMouseClicked

    private void btnProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvMouseClicked
        // TODO add your handling code here:
        numReporte = 1;
        limpiarTabla();
        cargarTabla(encabezadosProvs);
    }//GEN-LAST:event_btnProvMouseClicked

    private void btnCategMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategMouseClicked
        // TODO add your handling code here:
        numReporte = 2;
        limpiarTabla();
        cargarTabla(nomCategorias);
    }//GEN-LAST:event_btnCategMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        vMenu vMenu = new vMenu();
        vMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ReportGenerator1 rpt = new ReportGenerator1();
        if(this.numReporte == 0) {
            rpt.generarReporte("src\\main\\java\\reportes\\reporteProductos.jasper");
        }
        if(this.numReporte == 1) {
            rpt.generarReporte("src\\main\\java\\reportes\\reporteProveedores.jasper");
        }
        if(this.numReporte == 2) {
            rpt.generarReporte("src\\main\\java\\reportes\\reporteCategorias.jasper");
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vCrearReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vCrearReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vCrearReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vCrearReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vCrearReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCateg;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProv;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
